FROM appbase

RUN apt-get install -yq x11-common x11-utils x11-xserver-utils
RUN apt-get install -yq chromium

ENTRYPOINT ["chromium"]
CMD ["--no-sandbox"]

RUN mkdir /.config/
RUN mkdir /.pki/
RUN chown dockerx:users /.config/
RUN chown dockerx:users /.pki/
RUN chmod 777 /.config
RUN chmod 777 /.pki
#USER dockerx
VOLUME ["/.config", "/.pki"]
